name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_ischoolapi:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ '4bf17563-ed01-4cfb-929f-5a1a3b2ba2f4' }}
        APP_NAME: ${{ 'ischoolapi' }}
      run: |
        cd ./ASPNetCoreLabs/HerokuContainer
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
