# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_ischoolapi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'ischoolapi' }}
      run: |
        cd ./ASPNetCoreLabs/HerokuContainer
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
